apply plugin: 'org.springframework.boot'

dependencies {
    implementation project(':model')
    implementation project(':rest-documentos')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    runtimeOnly('org.springframework.boot:spring-boot-devtools')
    testImplementation 'com.tngtech.archunit:archunit:1.4.2'
    testImplementation 'org.springframework.security:spring-security-test'
}

tasks.register('explodedJar', Copy) {
    with jar
    into layout.buildDirectory.dir("exploded")
}

jar {
    enabled = false
}

bootJar {
    archiveFileName = "${project.getParent().getName()}.${archiveExtension.get()}"
}
