pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

buildCache {
    local {
        directory = new File(rootDir, 'build-cache')
    }
}

rootProject.name = '3-Excepciones'

include ':app-service'
include ':model'
project(':app-service').projectDir = file('./applications/app-service')
project(':model').projectDir = file('./domain/model')
