server:
  port: 8080
spring:
  application:
    name: 16-EDA
  devtools:
    add-properties: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: citas-recordatorios
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.value.default.type: pragma.model.CitaReservada
        spring.json.trusted.packages: pragma.model
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: false
