pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

buildCache {
    local {
        directory = new File(rootDir, 'build-cache')
    }
}

rootProject.name = '13-Resiliencia'

include ':app-service'
include ':model'
project(':app-service').projectDir = file('./applications/app-service')
project(':model').projectDir = file('./domain/model')
include ':usecase'
project(':usecase').projectDir = file('./domain/usecase')
include ':pasarela-pagos'
project(':pasarela-pagos').projectDir = file('./infrastructure/driven-adapters/pasarela-pagos')
